import Head from 'next/head'
import styles from './index/Index.module.css'

import dynamic from 'next/dynamic';

const MapWithNoSSR = dynamic(() => import('./components/Map/Map'), {
    ssr: false,
});

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Saigon Code Workspace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/public/favicon.ico" />
      </Head>

      <main className={styles.main}>
          <div style={{ height: "100vh", width: "100%"}}>
            <MapWithNoSSR/>
          </div>
      </main>
    </div>
  )
}
